<?php

declare(strict_types=1);

namespace gordonmcvey\WarpCore\test\Spies;

use gordonmcvey\httpsupport\interface\response\ResponseInterface;
use gordonmcvey\httpsupport\interface\response\ResponseSenderInterface;

/**
 * Sender Spy
 *
 * This class is used in integration tests to capture the response generated by the front controller so we can do
 * assertions on it
 */
class SenderSpy implements ResponseSenderInterface
{
    public ?ResponseInterface $lastResponse = null;

    public function send(ResponseInterface $response): ResponseSenderInterface
    {
        $this->lastResponse = $response;
        return $this;
    }

    public function sendHeaders(ResponseInterface $response): ResponseSenderInterface
    {
        return $this;
    }

    public function sendBody(ResponseInterface $response): ResponseSenderInterface
    {
        return $this;
    }
}
